title: "[WEEK] Weekly Progress"
labels: ["weekly-progress"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🗓️ Weekly Progress

        이번 주 목표와 진행 상황을 아래 표에 작성해주세요.

        | 이름 | 이번 주 목표 | 진행 상황 | 비고 |
        |:---|:---|:---|:---|
        |  |  |  |  |
        |  |  |  |  |

  - type: textarea
    id: extra-notes
    attributes:
      label: 추가 메모
      description: 추가로 작성할 내용이 있다면 여기에 작성하세요
      placeholder: "예시) 팀 회의 일정, 특이사항 등"
    validations:
      required: false
