title: "[WEEK] Weekly Progress"
labels: ["weekly-progress"]
body:
  - type: markdown
    attributes:
      value: |
        이번 주 목표와 진행 상황을 작성해주세요!
  - type: textarea
    id: weekly-progress
    attributes:
      label: 이번 주 목표 및 진행 상황
      description: 이름, 이번 주 목표, 진행 상황을 표 형식으로 작성해주세요.
      placeholder: "예시: | 이름 | 이번 주 목표 | 진행 상황 | 비고 |"
      value: |
        | 이름 | 이번 주 목표 | 진행 상황 | 비고 |
        |:---|:---|:---|:---|
        | 권재은 | | | |
        | 이우창 | | | |
        | 인성준 | | | |
        | 지윤식 | | | |
        | 박범진 | | | |
        | 정휘상 | | | |
      render: bash
    validations:
      required: true
