title: "[WEEK] Weekly Progress"
labels: ["weekly-progress"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🗓️ Weekly Progress

        이번 주 목표와 진행 상황을 아래 표에 작성해 주세요.

        | 이름 | 이번 주 목표 | 진행 상황 | 비고 |
        |:---|:---|:---|:---|
        |  |  |  |  |
        |  |  |  |  |

        > 진행 중인 내용을 매주 업데이트해주세요!
