spring:
  application:
    name: OhTalkHae
  web:
    resources:
      add-mappings: false
  jwt:
    secret: ${JWT_SECRET}
    refresh-token-expiration-time: 43200000
    access-token-expiration-time: 3600000
  datasource:
    url: jdbc:h2:mem:ohtalkhae
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
file:
  upload:
    path: ./upload/profile/
